- hosts: all
  remote_user: ec2-user
  become: yes
  
  tasks:
    - name: change dir and run the command
      command: sed -i 's/#fff/#768331/g' wp-content/themes/twentyfifteen/style.css
      args:
        chdir: /tmp/WordPress



   


        



      